const AUTH_TYPES = {
  RESET_STATE: 'RESET_STATE',

  UPDATE_USER_DATA: 'UPDATE_USER_DATA',

  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_NO_2FA_SUCCESS: 'LOGIN_NO_2FA_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REFRESH_TOKEN_BEGIN: 'REFRESH_TOKEN_BEGIN',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

  CHANGE_PASSWORD_BEGIN: 'CHANGE_PASSWORD_BEGIN',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',


  SET_SUBMITTING: 'SET_SUBMITTING',

  LOGOUT: 'LOGOUT',
};

export default AUTH_TYPES;
